name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile project
      run: |
        # 运行 make 命令
        make
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          **/*            # 上传所有文件和文件夹
        if-no-files-found: warn  # 如果没有文件匹配，则发出警告